# Override file for local development
version: '3.8'

services:
  app-dev:
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://mongo:27017/fuel_truck_db
      SESSION_SECRET: fuel_truck_session_secret_dev_2024
      PORT: 5001
      # Enable hot reload
      VITE_HOST: 0.0.0.0
    stdin_open: true
    tty: true

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fuel_truck_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local