# Production configuration
#version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/fuel_truck_db
      SESSION_SECRET: ${SESSION_SECRET:-fuel_truck_session_secret_prod_2024}
      PORT: 5001
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - fuel-truck-network

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fuel_truck_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local