# Production configuration
version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://fuel_admin:fuel_secure_pass_2024@postgres:5432/fuel_truck_db
      SESSION_SECRET: ${SESSION_SECRET:-fuel_truck_session_secret_prod_2024}
      PORT: 5001
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fuel-truck-network

  postgres:
    environment:
      POSTGRES_DB: fuel_truck_db
      POSTGRES_USER: fuel_admin
      POSTGRES_PASSWORD: fuel_secure_pass_2024
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
    driver: local