# Production configuration
#version: '3.8'

services:
  app-prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/fuel_truck_db
      SESSION_SECRET: ${SESSION_SECRET:-fuel_truck_session_secret_prod_2024}
      PORT: 5001
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-fuelogistics}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-fuelogistics123}
      MINIO_BUCKET: fuelogistics-files
      MINIO_USE_SSL: false
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - fuel-truck-network

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fuel_truck_db
    volumes:
      - mongo_data:/data/db
    networks:
      - fuel-truck-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO for file storage
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelogistics}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-fuelogistics123}
      MINIO_DEFAULT_BUCKETS: fuelogistics-files
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - fuel-truck-network
    healthcheck:
      disable: true

  # MinIO bucket initialization
  minio-init:
    image: minio/mc:RELEASE.2024-01-13T08-44-48Z
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-fuelogistics}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-fuelogistics123}
    networks:
      - fuel-truck-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER:-fuelogistics} ${MINIO_ROOT_PASSWORD:-fuelogistics123};
      /usr/bin/mc mb --ignore-existing minio/fuelogistics-files;
      /usr/bin/mc policy set public minio/fuelogistics-files;
      echo 'MinIO bucket configured successfully';
      "

networks:
  fuel-truck-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local